name: CI/CD

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Simulando deploy
        run: echo "Deploy realizado com sucesso!"

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()

    steps:
      - name: Notificar Discord
        run: |
          STATUS="SUCESSO"
          if [ "${{ needs.build.result }}" != "success" ] || [ "${{ needs.deploy.result }}" != "success" ]; then
            STATUS="FALHA"
          fi

          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"🚀 Pipeline finalizado: $STATUS no repositório ${{ github.repository }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
